--EJERCICIOS EVALUABLES UNIDAD 4--

----------------------------------
----------ACTIVIDAD 1-------------
----------------------------------

DROP DATABASE ACTIVIDAD_1
GO
USE MASTER
GO
CREATE DATABASE ACTIVIDAD_1
GO
USE ACTIVIDAD_1
GO
CREATE TABLE PAISES (
		codPais CHAR(2) NOT NULL,
		nombre VARCHAR(75) NOT NULL,
		
		CONSTRAINT PK_PAISES PRIMARY KEY(codPais)
)
GO
CREATE INDEX IX_PAISES
ON PAISES(nombre);
GO
CREATE TABLE ESCUELAS (
		codEscuela INT IDENTITY NOT NULL,
		nombre VARCHAR(75) NOT NULL,
		codPais CHAR(2) NOT NULL,
		fechaAlta SMALLDATETIME NOT NULL

		CONSTRAINT PK_ESCUELAS PRIMARY KEY(codEscuela),
		CONSTRAINT FK_PAISES_ESCUELAS FOREIGN KEY(codPais) REFERENCES PAISES(codPais)
)
GO
CREATE INDEX IX_ESCUELAS
ON ESCUELAS(nombre);
GO
CREATE TABLE PINTORES (
		codPintor INT IDENTITY NOT NULL,
		codPintorMaestro INT NOT NULL,
		nombre VARCHAR(150) NOT NULL,
		codPais CHAR(2) NOT NULL,
		codEscuela INT NOT NULL

		CONSTRAINT PK_PINTORES PRIMARY KEY(codPintor),
		CONSTRAINT FK_PINTORMAESTRO_PINTOR FOREIGN KEY(codPintorMaestro) REFERENCES PINTORES(codPintor),
		CONSTRAINT FK_ESCUELAS_PINTORES FOREIGN KEY(codEscuela) REFERENCES ESCUELAS(codEscuela),
		CONSTRAINT FK_PAISES_PINTORES FOREIGN KEY(codPais) REFERENCES PAISES(codPais)
)
GO
CREATE INDEX IX_PINTORES
ON PINTORES(nombre);
GO
CREATE TABLE GALERIAS ( 
		codGaleria INT IDENTITY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		ciudad VARCHAR(75) NOT NULL,
		dirección VARCHAR(250) NOT NULL,
		metrosCuadrados DECIMAL(7,2) NOT NULL

		CONSTRAINT PK_GALERIAS PRIMARY KEY(codGaleria)
)
GO
CREATE INDEX IX_GALERIAS
ON GALERIAS(nombre);
GO
CREATE TABLE CUADROS (
		codCuadro INT IDENTITY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		altura_cm DECIMAL(4,2) NOT NULL,
		anchura_cm DECIMAL(4,2) NOT NULL,
		dimension_cm_Cuadrados AS altura_cm * anchura_cm,
		fecha SMALLDATETIME NOT NULL,
		tecnica VARCHAR(100) NOT NULL,
		codGaleria INT NOT NULL,
		codPintor INT NOT NULL


		CONSTRAINT PK_CUADROS PRIMARY KEY(codCuadro),
		CONSTRAINT FK_GALERIAS_CUADROS FOREIGN KEY(codGaleria) REFERENCES GALERIAS(codGaleria),
		CONSTRAINT FK_PINTORES_CUADROS FOREIGN KEY(codPintor) REFERENCES PINTORES(codPintor)
)
GO
CREATE INDEX IX_CUADROS
ON CUADROS(nombre);	
GO
CREATE TABLE PATROCINADORES (
		codPatrocinador INT IDENTITY NOT NULL,
		nombre VARCHAR(150) NOT NULL,
		codPais CHAR(2) NOT NULL,

		CONSTRAINT PK_PATROCINADORES PRIMARY KEY(codPatrocinador),
		CONSTRAINT FK_PAISES_PATROCINADORES FOREIGN KEY(codPais) REFERENCES PAISES(codPais)
)
GO
CREATE INDEX IX_PATROCINADORES
ON PATROCINADORES(nombre);
GO
CREATE TABLE PATROCINADORES_MECENAS (
		codPatrocinador INT  NOT NULL,
		codPintor INT NOT NULL

		CONSTRAINT PK_PATROCINADORES_PINTORES PRIMARY KEY(codPatrocinador, codPintor),
		CONSTRAINT FK_PATROCINADORES_PATROCINADOR_MECENAS FOREIGN KEY (codPatrocinador) REFERENCES PATROCINADORES(codPatrocinador),
		CONSTRAINT FK_PINTORES_PATROCINADOR_MECENAS FOREIGN KEY(codPintor) REFERENCES PINTORES(codPintor)
)

----------------------------------
----------ACTIVIDAD 2-------------
----------------------------------

DROP DATABASE ACTIVIDAD_2
GO
USE MASTER
GO
CREATE DATABASE ACTIVIDAD_2
GO
USE ACTIVIDAD_2
CREATE TABLE PROVINCIAS (
		codProv INT IDENTITY NOT NULL,
		nombre VARCHAR(50) NOT NULL,

		CONSTRAINT PK_PROVINCIAS PRIMARY KEY(codProv),
)
GO
CREATE INDEX IX_PROVINCIAS
ON PROVINCIAS(nombre);	
GO
CREATE TABLE MUNICIPIOS (
		codMuni INT IDENTITY NOT NULL,
		codProv INT NOT NULL,
		nombre VARCHAR(100) NOT NULL

		CONSTRAINT PK_MUNICIPIOS PRIMARY KEY(codMuni,codProv),
		CONSTRAINT FK_PROVINCIAS_MUNICIPIOS FOREIGN KEY(codProv) REFERENCES PROVINCIAS(codProv)
)
GO
CREATE INDEX IX_MUNICIPIOS
ON MUNICIPIOS(nombre);	
GO
CREATE TABLE IMPUESTOS (
		codImpuesto INT NOT NULL,
		importe DECIMAL(16,2) NOT NULL,
		fechaMaxPago SMALLDATETIME NOT NULL,
		anyo DECIMAL(4,0) NOT NULL


		CONSTRAINT PK_IMPUESTOS PRIMARY KEY(codImpuesto),
)
GO
CREATE INDEX IX_IMPUESTOS
ON IMPUESTOS(importe);	
GO
CREATE TABLE IMPUESTOS_IBI (
		codImpuesto INT NOT NULL,
		valorCatastral DECIMAL (16,2) NOT NULL,
		tipoImpositivo DECIMAL (4,2) NOT NULL

		CONSTRAINT PK_IMPUESTOS_IBI PRIMARY KEY (codImpuesto),
		CONSTRAINT FK_IMPUESTOS_IMPUESTOS_IBI FOREIGN KEY (codImpuesto) REFERENCES IMPUESTOS(codImpuesto)
)
GO	
CREATE TABLE IMPUESTOS_IVTM (
		codImpuesto INT NOT NULL,
		tipoVehiculo VARCHAR(100) NOT NULL,
		caballosFiscales DECIMAL (4,2) NOT NULL

		CONSTRAINT PK_IMPUESTOS_IVTM PRIMARY KEY (codImpuesto),
		CONSTRAINT FK_IMPUESTOS_IMPUESTOS_IVTM FOREIGN KEY (codImpuesto) REFERENCES IMPUESTOS(codImpuesto)
)
GO
CREATE TABLE IMPUESTOS_IAE (
		codImpuesto INT NOT NULL,
		facturaMediaAnual DECIMAL (12,2) NOT NULL

		CONSTRAINT PK_IMPUESTOS_IAE PRIMARY KEY (codImpuesto),
		CONSTRAINT FK_IMPUESTOS_IMPUESTOS_IAE FOREIGN KEY (codImpuesto) REFERENCES IMPUESTOS(codImpuesto)
)
GO
CREATE TABLE CONTRIBUYENTES (
		NIF CHAR(10) NOT NULL,
		nombre VARCHAR(50) NOT NULL,
		apellido1 VARCHAR(50) NOT NULL,
		apellido2 VARCHAR(50) NOT NULL,
		dirección VARCHAR(250) NOT NULL,
		codPostal CHAR(5) NOT NULL

		CONSTRAINT PK_CONTRIBUYENTES PRIMARY KEY(NIF),
)
GO
CREATE INDEX IX_CONTRIBUYENTES
ON CONTRIBUYENTES(nombre);
GO
CREATE TABLE OFICINAS (
		codOficina INT IDENTITY NOT NULL,
		nombre VARCHAR(50) NOT NULL,
		dirección VARCHAR(250) NOT NULL

		CONSTRAINT PK_OFICINAS PRIMARY KEY(codOficina)
)
GO
CREATE INDEX IX_OFICINAS
ON OFICINAS(nombre);
GO
CREATE TABLE MODOS_PAGO (
		modoPago CHAR(1) NOT NULL,
		descripción VARCHAR(50) NOT NULL,
		activoSN BIT NOT NULL

		CONSTRAINT PK_MODOS_PAGO PRIMARY KEY (modoPago)
)
GO
CREATE INDEX IX_MODOS_PAGO
ON MODOS_PAGO(descripción);
GO
CREATE TABLE PAGOS (
		fechaHora SMALLDATETIME NOT NULL,
		modoPago CHAR(1) NOT NULL,
		NIF CHAR(10) NOT NULL,
		codOficina INT NOT NULL,
		codImpuesto INT NOT NULL

		CONSTRAINT PK_PAGOS_IMPUESTOS_CONTRIBUYENTES PRIMARY KEY(codImpuesto,NIF),
		CONSTRAINT FK_MODOS_PAGO_PAGOS FOREIGN KEY(modoPago) REFERENCES MODOS_PAGO(modoPago),
		CONSTRAINT FK_CONTRIBUYENTES_PAGOS FOREIGN KEY(NIF) REFERENCES CONTRIBUYENTES(NIF),
		CONSTRAINT FK_OFICINAS_PAGOS FOREIGN KEY(codOficina) REFERENCES OFICINAS(codOficina),
		CONSTRAINT FK_IMPUESTOS_PAGOS FOREIGN KEY(codImpuesto) REFERENCES IMPUESTOS(codImpuesto)
)
GO
CREATE INDEX IX_PAGOS
ON PAGOS(fechaHora);


----------------------------------
----------ACTIVIDAD 3-------------
----------------------------------

DROP DATABASE ACTIVIDAD_3
GO
USE MASTER
GO
CREATE DATABASE ACTIVIDAD_3
GO
USE ACTIVIDAD_3
CREATE TABLE CATEGORIAS (
		codCategoria INT IDENTITY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		IVA DECIMAL(4,2) NOT NULL

		CONSTRAINT PK_CATEGORIAS PRIMARY KEY(codCategoria)
)
GO
CREATE INDEX IX_CATEGORIAS
ON CATEGORIAS(nombre);
GO
CREATE TABLE HOTELES (
		codHotel INT IDENTITY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		dirección VARCHAR(250) NOT NULL,
		teléfono CHAR(9) NOT NULL,
		codCategoria INT NOT NULL

		CONSTRAINT PK_HOTELES PRIMARY KEY(codHotel),
		CONSTRAINT FK_CATEGORIAS_HOTELES FOREIGN KEY(codCategoria) REFERENCES CATEGORIAS(codCategoria),
)
GO
CREATE INDEX IX_HOTELES
ON HOTELES(nombre);
GO
CREATE TABLE HABITACIONES (
		codHabitacion CHAR(4) NOT NULL,
		codHotel INT NOT NULL,
		tipoHabitacion VARCHAR(100) NOT NULL,
		precio DECIMAL(7,2) NOT NULL,

		CONSTRAINT PK_HABITACIONES_HOTELES PRIMARY KEY(codHotel,codHabitacion),
		CONSTRAINT FK_HOTELES_HABITACIONES FOREIGN KEY(codHotel) REFERENCES HOTELES(codHotel)
)
GO
CREATE INDEX IX_HABITACIONES
ON HABITACIONES(precio);
GO
CREATE TABLE CLIENTES (
		codCliente INT IDENTITY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		dirección VARCHAR(250) NOT NULL,
		teléfono CHAR(9) NOT NULL

		CONSTRAINT PK_CLIENTES PRIMARY KEY(codCliente),
)
GO
CREATE INDEX IX_CLIENTES
ON CLIENTES(nombre);
GO
CREATE TABLE CLIENTES_PARTICULARES (
		codCliente INT NOT NULL,
		DNI CHAR(10) NOT NULL


		CONSTRAINT PK_CLIENTES_PARTICULARES PRIMARY KEY(codCliente),
		CONSTRAINT FK_CLIENTES_CLIENTES_PARTICULARES FOREIGN KEY(codCliente) REFERENCES CLIENTES(codCliente)
)
GO
CREATE TABLE CLIENTES_AGENCIAS (
		codCliente INT NOT NULL,
		nombreAgencia VARCHAR(100) NOT NULL

		CONSTRAINT PK_CLIENTES_AGENCIAS PRIMARY KEY(codCliente),
		CONSTRAINT FK_CLIENTES_CLIENTES_AGENCIAS FOREIGN KEY(codCliente) REFERENCES CLIENTES(codCliente),
)
GO
CREATE TABLE RESERVAS_HABITACIONES_CLIENTES (
		codReserva INT IDENTITY NOT NULL,
		codHotel INT NOT NULL,
		codHabitacion CHAR(4) NOT NULL,
		codCliente INT NOT NULL,
		fechaInicio SMALLDATETIME NOT NULL,
		fechaFin SMALLDATETIME NOT NULL,
		precioTotal DECIMAL(7,2) NOT NULL

		CONSTRAINT PK_RESERVAS_HABITACIONES_CLIENTES PRIMARY KEY(codReserva),
		CONSTRAINT FK_HOTELES_HABITACIONES_RESERVAS_HABITACIONES_CLIENTES FOREIGN KEY(codHotel,codHabitacion) REFERENCES HABITACIONES(codHotel,codHabitacion),
		CONSTRAINT FK_CLIENTES_RESERVAS_HABITACIONES_CLIENTES FOREIGN KEY(codCliente) REFERENCES CLIENTES(codCliente)
)
GO
CREATE INDEX IX_RESERVAS_HABITACIONES_CLIENTES
ON RESERVAS_HABITACIONES_CLIENTES(precioTotal);
