--------------------------------------------------
-- SCRIPT DE CREACION DE LA BASE DE DATOS TIENDA
--------------------------------------------------

CREATE DATABASE TIENDAREPASO
GO
USE TIENDAREPASO
GO

-- Creaci�n de la tabla FABRICANTE
CREATE TABLE FABRICANTE (
  codigo INT IDENTITY(1,1),
  nombre VARCHAR(100) NOT NULL
  CONSTRAINT PK_FABRICANTE PRIMARY KEY (codigo)
);


-- Creaci�n de la tabla PRODUCTO
CREATE TABLE PRODUCTO (
  codigo INT IDENTITY(1,1),
  nombre VARCHAR(100) NOT NULL,
  precio DECIMAL(9,2) NOT NULL,
  codigo_fabricante INT NOT NULL
  CONSTRAINT PK_PRODUCTO PRIMARY KEY (codigo)
  FOREIGN KEY (codigo_fabricante) REFERENCES FABRICANTE(codigo)
);

-- Inserci�n de datos en la tabla FABRICANTE
INSERT INTO FABRICANTE VALUES('Asus');
INSERT INTO FABRICANTE VALUES('Lenovo');
INSERT INTO FABRICANTE VALUES('Hewlett-Packard');
INSERT INTO FABRICANTE VALUES('Samsung');
INSERT INTO FABRICANTE VALUES('Seagate');
INSERT INTO FABRICANTE VALUES('Crucial');
INSERT INTO FABRICANTE VALUES('Gigabyte');
INSERT INTO FABRICANTE VALUES('Huawei');
INSERT INTO FABRICANTE VALUES('Xiaomi');

-- Inserci�n de datos en la tabla PRODUCTO
INSERT INTO PRODUCTO VALUES('Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO PRODUCTO VALUES('Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO PRODUCTO VALUES('Disco SSD 1 TB', 150.99, 4);
INSERT INTO PRODUCTO VALUES('GeForce GTX 1050Ti', 185, 7);
INSERT INTO PRODUCTO VALUES('GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO PRODUCTO VALUES('Monitor 24 LED Full HD', 202, 1);
INSERT INTO PRODUCTO VALUES('Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO PRODUCTO VALUES('Port�til Yoga 520', 559, 2);
INSERT INTO PRODUCTO VALUES('Port�til Ideapad 320', 444, 2);
INSERT INTO PRODUCTO VALUES('Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO PRODUCTO VALUES('Impresora HP Laserjet Pro M26nw', 180, 3);
